name: Release CI

on:
  push:
    branches: [main, v2-maintenance]
  pull_request:
    branches: [main, v2-maintenance]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          # cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build lib
        run: npm run build
      - name: Jest run
        run: npm run test:unit
      - name: Release
        working-directory: lib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
